FROM alpine:3.1

# Update
RUN apk add --update python py-pip

# Install app dependencies
RUN pip install -r requirements.txt

# Bundle app source
COPY url_shortener.py /src/url_shortener.py

EXPOSE  8000
CMD ["python", "/src/url_shortener.py"]

